version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_api
    ports:
      - "8080:8080" # Menghubungkan port 8080 container ke host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://<MYSQL_HOST>:3306/<DATABASE_NAME>
      - SPRING_DATASOURCE_USERNAME=<MYSQL_USERNAME>
      - SPRING_DATASOURCE_PASSWORD=<MYSQL_PASSWORD>
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
